//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TBotStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TBotStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.TBotStrings", typeof(TBotStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChatBot is now disabled.
        /// </summary>
        public static string DisabledChatbot {
            get {
                return ResourceManager.GetString("DisabledChatbot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chatbot is now enabled.
        /// </summary>
        public static string EnabledChatBot {
            get {
                return ResourceManager.GetString("EnabledChatBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument to command can not be null or empty.
        /// </summary>
        public static string TBotCMDArgumentMissing {
            get {
                return ResourceManager.GetString("TBotCMDArgumentMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong argument provided.
        /// </summary>
        public static string TBotCMDWrongArg {
            get {
                return ResourceManager.GetString("TBotCMDWrongArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is now offdaline.
        /// </summary>
        public static string TBotGoodByeMSG {
            get {
                return ResourceManager.GetString("TBotGoodByeMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ondaline.
        /// </summary>
        public static string TBotGreetingMSG {
            get {
                return ResourceManager.GetString("TBotGreetingMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user created? : {0}.
        /// </summary>
        public static string TBotNewUserCreted {
            get {
                return ResourceManager.GetString("TBotNewUserCreted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed while creating a nerw user, missing parameter -&gt; !sqlinsertuser nickName isAdmin(true or false).
        /// </summary>
        public static string TBotNewUserParameterMising {
            get {
                return ResourceManager.GetString("TBotNewUserParameterMising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not this bot admin, you should either erase the current DB or use an SQLite broswer to change its data. The database can be found at {0}.
        /// </summary>
        public static string TBotNotThisBotAdmin {
            get {
                return ResourceManager.GetString("TBotNotThisBotAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no users on database, we need to set up the admin.
        /// </summary>
        public static string TBotNoUsersOnDB {
            get {
                return ResourceManager.GetString("TBotNoUsersOnDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with ID: {0} removed?: {1}.
        /// </summary>
        public static string TBotUserIDRemoved {
            get {
                return ResourceManager.GetString("TBotUserIDRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User: {0} removed?: {1}.
        /// </summary>
        public static string TBotUserNameRemoved {
            get {
                return ResourceManager.GetString("TBotUserNameRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID: {0}{1}Username: {2}{3}IsAdmin: {4} .
        /// </summary>
        public static string TBotUsersChatMSG {
            get {
                return ResourceManager.GetString("TBotUsersChatMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User admin status updated: {0}.
        /// </summary>
        public static string TBotUserUpdated {
            get {
                return ResourceManager.GetString("TBotUserUpdated", resourceCulture);
            }
        }
    }
}
